version: '3.8'

services:
  frontend-dev:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - deployhub-network

  backend-dev:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=4000
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - deployhub-network

networks:
  deployhub-network:
    driver: bridge
