services:
  # Backend API Service
  - type: web
    name: deployhub-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: FRONTEND_URL
        value: https://deployhub-frontend.onrender.com
    rootDir: .

  # Frontend Static Site
  - type: static
    name: deployhub-frontend
    buildCommand: cd frontend/web && npm install && npx vite build
    publishPath: frontend/web/dist
    envVars:
      - key: VITE_SERVER_ORIGIN
        value: https://deployhub-backend.onrender.com
    rootDir: .
